### ISSUE TITLE
Karma Test in Chrome failed at getWindowByRef

### ISSUE THREAD

**Issue by sytong** [krakenjs/zoid#209]
I started my project using the `grumbler` template and I have reconfigured Karma by referring to the latest version of the `zoid-demo`. I can successfully run my test case (just one for now)  without a browser.

However when I tried to run it using Chrome (with the below command line) and clicked the *DEBUG* button, in the new browser tab my Button failed to render:
```
npm run karma -- --browser=Chrome --keep-open
```

I saw this error in the console. Apparently, when the parent of the Child window is of type *global*, `getWindowByRef` could not find the window. 
```
Uncaught Error: Error: Unable to find global window
    at ChildComponent.getWindowByRef (http://localhost:9876/base/test/windows/button/index.js:10563:13)
    at http://localhost:9876/base/test/windows/button/index.js:10432:43
    at Function._try [as try] (http://localhost:9876/base/test/windows/button/index.js:10291:23)
    at new ChildComponent (http://localhost:9876/base/test/windows/button/index.js:10420:71)
    at Component.registerChild (http://localhost:9876/base/test/windows/button/index.js:10964:19)
    at new Component (http://localhost:9876/base/test/windows/button/index.js:10917:10)
    at create (http://localhost:9876/base/test/windows/button/index.js:11148:19)
    at Module../src/button/component.jsx (http://localhost:9876/base/test/windows/button/index.js:13502:93)
    at __webpack_require__ (http://localhost:9876/base/test/windows/button/index.js:30:30)
    at Module../src/button/index.js (http://localhost:9876/base/test/windows/button/index.js:13600:68)
```

I saw some latest code change related to `getWindowByRef` (was removed?). I wonder if the recent unreleased code change is related to this issue?

**Comment by sytong** [comment]
Apologies.
I figured this out.
I made a mistake with the mock domain.
Now I can display the button in the Karma browser.
